#
# Configuration
#
language: cpp
dist: trusty

#
# Build Dependencies
#
before_script:

  #
  # Path
  #
  - export PATH="$HOME/bfprefix/bin:$PATH"

  #
  # Build Folder
  #
  - mkdir build
  - cd build

  #
  # Update / Install CMake
  #
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p external/cmake
      pushd external/cmake
      wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
      chmod +x cmake-*-Linux-x86_64.sh
      ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
      export PATH="${PWD}/bin:$PATH"
      popd
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi

  #
  # bfsdk
  #
  - git clone https://github.com/Bareflank/bfsdk.git
  - mkdir bfsdk/build
  - pushd bfsdk/build
  - |
    cmake \
      -DCMAKE_C_COMPILER="gcc-6" \
      -DCMAKE_CXX_COMPILER="g++-6" \
      ..
  - make install
  - popd
  - rm -Rf bfsdk

#
# Build Matrix
#
matrix:
  include:

  #
  # Git Check
  #
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
          - nasm
    env:
      - TEST="Git Check"
    script:
      - |
        if [[ -n $(git diff --check HEAD^) ]]; then
          echo "You must remove whitespace before submitting a pull request"
          echo ""
          git diff --check HEAD^
          exit -1
        fi

  #
  # Build Test (Clang 3.8)
  #
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.8
        packages:
          - clang-3.8
          - gcc-6
          - g++-6
          - nasm
    env:
      - TEST="Build Test 3.8"
    script:
      - |
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=~/bfprefix/cmake/CMakeToolchain_VMM_38.txt \
          -DDISABLE_WARNINGS=on \
          ..
      - make

  #
  # Build Test (Clang 3.9)
  #
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-3.9
        packages:
          - clang-3.9
          - gcc-6
          - g++-6
          - nasm
    env:
      - TEST="Build Test 3.9"
    script:
      - |
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=~/bfprefix/cmake/CMakeToolchain_VMM_39.txt \
          -DDISABLE_WARNINGS=on \
          ..
      - make

  #
  # Build Test (Clang 4.0)
  #
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - clang-4.0
          - gcc-6
          - g++-6
          - nasm
    env:
      - TEST="Build Test 4.0"
    script:
      - |
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=~/bfprefix/cmake/CMakeToolchain_VMM_40.txt \
          -DDISABLE_WARNINGS=on \
          ..
      - make
