#
# Configuration
#

language: cpp

dist: trusty
sudo: required

#
# Compilers
#
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.8
      - llvm-toolchain-trusty-3.9
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-3.8
      - clang-3.9
      - clang-4.0
      - clang-tidy-4.0
      - clang-format-4.0
      - llvm-4.0
      - gcc-6
      - g++-6
      - nasm
      - doxygen

#
# Update Build Environment
#
# Currently GCC and CMake are out of date. We require:
# - GCC 5+
# - CMake 3.4+
#
# The following updates these packages, along with settings added to the addon
# pages like gcc. Also to keep things simple, we install cmake into the home
# directory. Finally, we add the bfprefix to the path so that installed scripts
# can be located
#
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  - chmod +x cmake-3.7.2-Linux-x86_64.sh
  - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100
  - export PATH="$HOME/bfprefix/bin:$PATH"

#
# Build Dependencies
#
before_script:
  - mkdir build
  - cd build

  #
  # bfsdk
  #
  - git clone https://github.com/Bareflank/bfsdk.git
  - mkdir bfsdk/build
  - pushd bfsdk/build
  - cmake ..
  - make install
  - popd

#
# Build Matrix
#
matrix:
  include:

  #
  # Git Check
  #
  - os: linux
    env:
      - TEST="Git Check"
    script:
      - |
        if [[ -n $(git diff --check HEAD^) ]]; then
          echo "You must remove whitespace before submitting a pull request"
          echo ""
          git diff --check HEAD^
          exit -1
        fi

  #
  # Build Test (Clang 3.8)
  #
  - os: linux
    env:
      - TEST="Build Test 3.8"
    script:
      - cmake -DCMAKE_TOOLCHAIN_FILE=~/bfprefix/cmake/CMakeToolchain_VMM_38.txt -DDISABLE_WARNINGS=on ..
      - make

  #
  # Build Test (Clang 3.9)
  #
  - os: linux
    env:
      - TEST="Build Test 3.9"
    script:
      - cmake -DCMAKE_TOOLCHAIN_FILE=~/bfprefix/cmake/CMakeToolchain_VMM_39.txt -DDISABLE_WARNINGS=on ..
      - make

  #
  # Build Test (Clang 4.0)
  #
  - os: linux
    env:
      - TEST="Build Test 4.0"
    script:
      - cmake -DCMAKE_TOOLCHAIN_FILE=~/bfprefix/cmake/CMakeToolchain_VMM_40.txt -DDISABLE_WARNINGS=on ..
      - make
